### ISSUE TITLE
Craftersshaft 

### ISSUE THREAD

**Issue by kayla-hue** [craftersshaft/craftersshaft.github.io#4]
Which hack is that for?

**Comment by ghost** [comment]
Please give more detail about your question so that I can help you with your issue.

**Comment by kayla-hue** [comment]
I just wanted to know if that's a hack but I can't really find other hacks cause they are patched

**Comment by ghost** [comment]
View the ProdigyMathGameHacking repo then; we don't provide hacks here.

**Comment by kayla-hue** [comment]
Chickennnn is this u from fandomm?

**Comment by ghost** [comment]
Yes, it is me from Fandom.

**Comment by kayla-hue** [comment]
Bruh, how did u got banned?

**Comment by ghost** [comment]
Here's the explanation I wrote to Rob:

> Okay, so, this is how I got global blocked:
> 
> About a month ago, Highlord's Crown main a wiki with the URL of mellowalker.fandom.com that is now deleted.
> 
> It was deleted because it was being used to make fun of and taunt other users, not document anything.
> 
> Well, Highlord's Crown had made me an admin there and asked me to fix the formatting of a page. I got blocked for "helping create a ToS-violating wiki", although, I had only 1 edit there.
> 
> I wasn't an active admin, and I think the bot banned me.

**Comment by 390922** [comment]
Sorry i could not find it but um the hack is for prodigy.

**Comment by ghost** [comment]
> Sorry i could not find it but um the hack is for prodigy.

https://Prodigy-Hacking/ProdigyMathGameHackinh

Now leave this repo alone.

**Comment by ghost** [comment]
@craftersshaft Can you please delete this issue? All the skiddies are gathering 'round and taking away from the point of this repo.
