### ISSUE TITLE
Prodigy Hack 

### ISSUE THREAD

**Issue by 390922** [craftersshaft/craftersshaft.github.io#6]
I can not find your newest prodigy hack can you do put it here?  That would be really helpful.  Thank you in advanced

**Comment by 390922** [comment]
Or just tell me what to search up in the search because I can not find it

**Comment by 390922** [comment]
Can somebody answer me?

**Comment by craftersshaft** [comment]
NAME ANYTHING CRAFTERSSHAFT HAS DONE BESIDES PRODIGYGAME HACKS CHALLENGE (100% WILL FAIL!!!!)
